name:                hw5
version:             0.1.0.0
github:              "githubuser/hw5"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/hw5#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 9.0
- parser-combinators
- text
- containers
- bytestring
- scientific
- prettyprinter
- prettyprinter-ansi-terminal
- mtl
- transformers
- time
- directory
- zlib
- serialise
- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hw5-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw5
    - haskeline

tests:
  hw5-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw5
