[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="message" type="java.lang.String" --]
[#-- @ftlvariable name="user" type="ru.itmo.wp.domain.User" --]
[#-- @ftlvariable name="userPage" type="ru.itmo.wp.domain.User" --]
