#define PE_SIGNATURE_SIZE 4
#define PE_SIGNATURE_SHIFT 0x3C
#define COFF_SIZE 20
#define OPTIONAL_HEADER_SIZE 240
#define SECTION_HEADER_SIZE 40
#define DEPENDENCY_SIZE 20

#define IMPORT_TABLE_ADDRESS_SHIFT 0x78
#define IMPORT_TABLE_SIZE_SHIFT (0x78 + 4)

#define EXPORT_TABLE_ADDRESS_SHIFT (0x78 - 8)

#define SECTION_VIRTUAL_SIZE_SHIFT 0x8
#define SECTION_RVA_SHIFT 0xC
#define SECTION_RAW_SHIFT 0x14

#define LEADING_BIT 0x8000000000000000

#define RVA_LIB_NAME_SHIFT 0xC
#define RVA_LIB_NAME_SIZE 4

#define LOOKUP_TABLE_RVA_SIZE 4

#define FOLLOWING_31_BITS 0x7FFFFFFF

#define EXPORT_CHARACTERISTICS_SHIFT 0xC
#define FIELD_SIZE_4 4