#!/usr/bin/env python3

from gradelib import *

r = Runner(save("xv6.out"))

@test(1, "pingpong")
def test_pingpong():
    r.run_qemu(shell_script([
        'pingpong',
        'echo OK'
    ]))
    r.match(
        '^\\d+: got ping$',
        '^\\d+: got pong$',
        '^OK$'
    )

@test(1, "pingpong, calls pipe")
def test_pingpong_pipe():
    r.run_qemu(shell_script([
        'pingpong',
        'echo FAIL'
    ]), stop_breakpoint('sys_pipe'))
    r.match(
        '\\$ pingpong',
        no=['FAIL']
    )

@test(1, "dump")
def test_dump():
    r.run_qemu(shell_script([
        'dumptests',
        'echo OK'
    ]))
    r.match(
        '^dump syscall found. Start testing$',
        '^4 tests were ran$',
        r'^\[DEBUG\] 2 3 4 5 6 7 8 9 10 11$',
        r'^\[DEBUG\] 1 -12 123 -1234 12345 -123456 1234567 -12345678 123456789 -1234567890$',
        r'^\[DEBUG\] 2147483647 -2147483648 1337 2020 3234 3235 3236 3237 3238 3239$',
        '^OK$',
        no=['^No dump syscall found. Stop testing$']
    )

run_tests()
