name: "cow"
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  basic:
    runs-on: [self-hosted, os]
    timeout-minutes: 1
    name: "Basic checks"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Check that branch has name 'cow'"
        run: |
          test "${GITHUB_HEAD_REF##*/}" = "cow"
      - name: "Lint source code"
        run: |
          clang-format --dry-run -Werror */*.c */*.h 2>clang-format.log || status=$?
          if [[ -n $status ]]; then
            cat clang-format.log |
              grep 'error:' |
              perl -pe 's/^((.*?):(.*?):(.*?):.*)$/::error file=\2,line=\3,col=\4::\1/g'
            exit $status
          fi
      - name: "Check hours.txt"
        run: |
          hours=$(cat hours.txt | tr -d '[:space:]')
          if [[ "$hours" == +([[:digit:]]) ]]; then
            echo "Hours spent: $hours"
          else
            echo "::error::Please fill in number of hours spent into hours.txt file."
            echo "::error::This file should contain exactly one number."
            exit 1
          fi
      - name: "Upload logs"
        uses: actions/upload-artifact@v4
        with:
          name: clang-format.log
          path: clang-format.log
        if: ${{ failure() }}
  tests:
    needs: basic
    runs-on: [self-hosted, os]
    timeout-minutes: 6
    name: "Required tests"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Run tests"
        run: ./grade
      - name: "Upload logs"
        uses: actions/upload-artifact@v4
        with:
          name: xv6.out
          path: xv6.out.*
        if: ${{ failure() }}
  slow-tests:
    needs: tests
    runs-on: [self-hosted, os]
    timeout-minutes: 16
    name: "Required tests (slow)"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Run tests"
        run: ./grade-slow
      - name: "Upload logs"
        uses: actions/upload-artifact@v4
        with:
          name: xv6.out
          path: xv6.out.*
        if: ${{ failure() }}
  lazy:
    needs: [basic, tests]
    runs-on: [self-hosted, os]
    timeout-minutes: 4
    continue-on-error: true
    name: "Bonus: lazy"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Run tests"
        run: ./grade-lazy
      - name: "Upload logs"
        uses: actions/upload-artifact@v4
        with:
          name: xv6.out
          path: xv6.out.*
        if: ${{ failure() }}
